"""Building Maintenance content added to the existing static site generator."""
from html import escape

CATEGORIES = [
 ('plumbing-maintenance',('Plumbing Maintenance','Mantenimiento de Plomería'),'32588548',('Technician working on a plumbing connection','Técnico trabajando en una conexión de plomería'),('Routine care for the fixtures and connections your building relies on.','Cuidado periódico de los accesorios y conexiones esenciales de su edificio.'),('Leaks|Faucets|Toilets|Sinks|Drain issues|Pipe repairs|Fixture replacement|Preventive plumbing inspections','Fugas|Grifos|Inodoros|Lavamanos|Problemas de drenaje|Reparación de tuberías|Reemplazo de accesorios|Inspecciones preventivas de plomería')),
 ('building-repairs',('General Building Repairs','Reparaciones Generales del Edificio'),'1505798577917-a65157d3320a',('Technician completing an interior repair','Técnico realizando una reparación interior'),('Address everyday wear in occupied spaces and shared areas.','Atención al desgaste cotidiano de espacios ocupados y zonas compartidas.'),('Minor repairs|Doors and hardware|Wall repairs|Caulking and sealing|Interior repairs|Common-area repairs','Reparaciones menores|Puertas y herrajes|Reparación de paredes|Sellado de juntas|Reparaciones interiores|Reparaciones en áreas comunes')),
 ('preventive-maintenance',('Preventive Maintenance','Mantenimiento Preventivo'),'8293680',('Property inspector reviewing an inspection checklist','Inspector revisando una lista de evaluación de la propiedad'),('Regular checks help identify visible issues and organize the next steps.','Las revisiones periódicas ayudan a detectar problemas visibles y organizar las acciones necesarias.'),('Scheduled property inspections|Identification of visible leaks|Plumbing fixture checks|Drain observations|Common-area inspections|Maintenance recommendations','Inspecciones programadas de la propiedad|Identificación de fugas visibles|Revisión de accesorios de plomería|Observación de drenajes|Inspección de áreas comunes|Recomendaciones de mantenimiento')),
 ('bathroom-maintenance',('Bathroom Maintenance','Mantenimiento de Baños'),'7745981',('Bathroom basin and plumbing fixtures','Lavamanos y accesorios de plomería en un baño'),('Keep shared and private bathrooms on a consistent maintenance schedule.','Mantenga los baños privados y compartidos dentro de un programa de cuidado constante.'),('Toilets|Faucets|Sinks|Shower fixtures|Drain problems|Caulking|Minor repairs','Inodoros|Grifos|Lavamanos|Accesorios de ducha|Problemas de drenaje|Sellado de juntas|Reparaciones menores')),
 ('kitchen-maintenance',('Kitchen / Utility Area Maintenance','Mantenimiento de Cocinas y Áreas de Servicio'),'kitchen-work',('Plumber checking connections beneath a kitchen sink','Plomero revisando conexiones bajo un fregadero'),('Care for frequently used fixtures, accessible plumbing and utility spaces.','Cuidado de accesorios de uso frecuente, plomería accesible y espacios de servicio.'),('Faucets|Sinks|Drain connections|Visible plumbing leaks|Fixture repairs|Utility-area maintenance','Grifos|Fregaderos|Conexiones de desagüe|Fugas visibles de plomería|Reparación de accesorios|Mantenimiento de áreas de servicio')),
 ('doors-hardware',('Doors & Hardware','Puertas y Herrajes'),'8276607',('Hand operating a commercial building door handle','Mano accionando la manija de una puerta de edificio'),('Small adjustments can help doors and their hardware function properly.','Los ajustes oportunos ayudan a mantener el funcionamiento de puertas y herrajes.'),('Doors not closing correctly|Adjustments|Hinges|Handles|Minor hardware repairs|Alignment','Puertas que no cierran correctamente|Ajustes|Bisagras|Manijas|Reparaciones menores de herrajes|Alineación')),
 ('common-areas',('Common Areas','Áreas Comunes'),'13144294',('Shared indoor corridor with doors and lighting','Pasillo interior compartido con puertas e iluminación'),('A coordinated approach to the spaces shared by occupants and visitors.','Un enfoque coordinado para los espacios que comparten ocupantes y visitantes.'),('Hallways|Utility rooms|Restrooms|Shared building areas|Minor repair and maintenance needs','Pasillos|Cuartos de servicio|Baños comunes|Áreas compartidas del edificio|Necesidades menores de reparación y mantenimiento')),
 ('priority-coordination',('Emergency / Priority Repair Coordination','Coordinación de Reparaciones Urgentes o Prioritarias'),'5658852',('Building utility pipework and valves','Tuberías y válvulas en un área técnica del edificio'),('Agreement clients have one point of contact to report issues. We evaluate the problem and coordinate the work according to the plan’s scope, availability and agreed response conditions.','Los clientes con un acuerdo cuentan con un contacto para reportar problemas. Evaluamos la situación y coordinamos el trabajo según el alcance, la disponibilidad y las condiciones de respuesta acordadas.'),('Issue reporting|Initial evaluation|Repair coordination|Updates to the property contact|Service under the agreed plan','Reporte de problemas|Evaluación inicial|Coordinación de reparaciones|Comunicación con el responsable de la propiedad|Servicio según el plan acordado')),
]

def maintenance_page(t, photo, link, wa):
 def c(pair):return t(*pair)
 def title(eyebrow,heading,desc=''):
  return f'<div class="section-heading"><p class="eyebrow">{eyebrow}</p><h2>{heading}</h2>{"<p>"+desc+"</p>" if desc else ""}</div>'
 def cta():
  return f'<div class="actions"><a class="btn" href="#maintenance-assessment">{t("Request a Maintenance Plan","Solicitar un Plan de Mantenimiento")} ↗</a><a class="btn outline" href="tel:+12393337935">{t("Call Now","Llamar Ahora")}</a></div>'
 out=f'''<section class="hero maintenance-hero"><div class="hero-photo">{photo('8293639',t('Building inspector reviewing the condition of a window','Inspector evaluando el estado de una ventana'),False)}</div><div class="wrap hero-content"><p class="eyebrow">{t('PLANNED CARE. A LASTING PARTNERSHIP.','CUIDADO PLANIFICADO. UNA RELACIÓN CONTINUA.')}</p><h1>{t('Building Maintenance','Mantenimiento de Edificios')}</h1><p class="maintenance-lead">{t('Reliable ongoing maintenance for residential and commercial properties.','Mantenimiento continuo y confiable para propiedades residenciales y comerciales.')}</p><p class="hero-description">{t('We help property owners and managers keep their buildings operating properly through scheduled maintenance, preventive inspections, repairs and ongoing service agreements.','Ayudamos a propietarios y administradores a mantener sus edificios en buen funcionamiento mediante mantenimiento programado, inspecciones preventivas, reparaciones y acuerdos de servicio continuo.')}</p>{cta()}<div class="hero-notes"><span>{t('Property owners & managers','Propietarios y administradores')}</span><span>{t('New York & New Jersey','Nueva York y Nueva Jersey')}</span></div></div></section>
 <nav class="maintenance-jumps" aria-label="{t('Building maintenance sections','Secciones de mantenimiento de edificios')}"><div class="wrap">'''
 for id,txt in [('partnership',('Our Approach','Nuestro Enfoque')),('how-it-works',('How It Works','Cómo Funciona')),('maintenance-services',('Services','Servicios')),('prevention',('Prevention','Prevención')),('maintenance-plans',('Maintenance Plans','Planes')),('maintenance-assessment',('Request Assessment','Solicitar Evaluación'))]:out+=f'<a href="#{id}">{c(txt)} <span aria-hidden="true">↗</span></a>'
 out+='</div></nav>'
 out+=f'''<section class="section" id="partnership"><div class="wrap intro-split"><div>{title(t('ONGOING BUILDING MAINTENANCE','MANTENIMIENTO CONTINUO DE EDIFICIOS'),t('One maintenance partner. One point of contact.','Un aliado de mantenimiento. Un solo punto de contacto.'))}<p>{t('Instead of finding a different contractor for every issue, work with NextPro as your ongoing maintenance partner for routine care, inspections and repair needs.','En lugar de buscar un contratista distinto ante cada problema, cuente con NextPro como su aliado continuo para el mantenimiento habitual, las inspecciones y las reparaciones.')}</p><p>{t('When a covered issue is reported, we evaluate the problem, coordinate the necessary work and help restore the affected system or area as efficiently as possible.','Cuando se reporta un problema cubierto por el acuerdo, evaluamos la situación, coordinamos el trabajo necesario y buscamos restablecer el sistema o área afectada de manera eficiente.')}</p><p class="scope-note">{t('Your agreement defines what is included. Services, frequency and response conditions are tailored to the building; work outside the agreed scope is reviewed separately.','Su acuerdo define qué está incluido. Los servicios, la frecuencia y las condiciones de respuesta se adaptan al edificio; los trabajos fuera del alcance se revisan por separado.')}</p></div><div class="intro-image">{photo('439391',t('Multifamily residential building','Edificio residencial multifamiliar'))}</div></div></section>'''
 steps=[('Property Assessment','Evaluación de la Propiedad','We evaluate the building, identify maintenance priorities and understand its specific needs.','Evaluamos el edificio, identificamos las prioridades de mantenimiento y conocemos sus necesidades particulares.'),('Custom Maintenance Plan','Plan de Mantenimiento a Medida','Together, we define the services, inspection schedule, maintenance frequency and scope of work.','Definimos los servicios, el calendario de inspecciones, la frecuencia y el alcance del trabajo.'),('Preventive & Routine Maintenance','Mantenimiento Preventivo y Periódico','Scheduled inspections and routine maintenance help identify visible problems before they grow into larger repairs.','Las inspecciones y el mantenimiento programados ayudan a detectar problemas visibles antes de que requieran reparaciones mayores.'),('Repair & Service Response','Atención y Coordinación de Reparaciones','When issues arise, the property manager has one contact to coordinate and perform the necessary work within the agreed scope.','Cuando surge un problema, el administrador tiene un solo contacto para coordinar y realizar el trabajo necesario dentro del alcance acordado.')]
 out+=f'<section class="section soft" id="how-it-works"><div class="wrap">{title(t("HOW IT WORKS","CÓMO FUNCIONA"),t("A clear plan from the first visit.","Un plan claro desde la primera visita."))}<div class="steps maintenance-steps">'
 for i,(a,b,d,f) in enumerate(steps):out+=f'<article><span class="step-number">0{i+1}</span><h3>{t(a,b)}</h3><p>{t(d,f)}</p></article>'
 out+='</div></div></section>'
 out+=f'<section class="section" id="maintenance-services"><div class="wrap">{title(t("BUILDING MAINTENANCE SERVICES","SERVICIOS DE MANTENIMIENTO DE EDIFICIOS"),t("Plumbing expertise. Broader building care.","Especialistas en plomería. Cuidado integral del edificio."),t("Select the services your property needs. The final maintenance agreement establishes the included work and any exclusions.","Seleccione los servicios que necesita su propiedad. El acuerdo final establece los trabajos incluidos y sus exclusiones."))}<div class="maintenance-cards">'
 for i,(id,heading,img,alt,desc,items) in enumerate(CATEGORIES):
  out+=f'<article class="card maintenance-card" id="{id}">{photo(img,c(alt))}<div class="card-body"><p class="eyebrow">{i+1:02d} / NEXTPRO</p><h3>{c(heading)}</h3><p>{c(desc)}</p><ul class="checks">'+''.join(f'<li>{item}</li>' for item in c(items).split('|'))+'</ul>'
  if i==0:out+=f'<a class="text-link" href="{link("plumbing")}">{t("Explore our Plumbing division","Conozca nuestra división de Plomería")} →</a>'
  out+='</div></article>'
 out+='</div></div></section>'
 risks=[('Small leak','Fuga pequeña','Water damage','Daños por agua'),('Loose fixture','Accesorio flojo','Larger repair','Reparación mayor'),('Slow drain','Drenaje lento','Possible blockage','Posible obstrucción'),('Damaged caulking','Sellado deteriorado','Moisture problems','Problemas de humedad'),('Door alignment issue','Puerta desalineada','Damaged hardware or frame','Daños en herrajes o marco')]
 out+=f'<section class="section prevention-section" id="prevention"><div class="wrap">{title(t("PREVENTIVE MAINTENANCE","MANTENIMIENTO PREVENTIVO"),t("Fix small problems before they become expensive problems.","Atienda los problemas pequeños antes de que se conviertan en reparaciones costosas."),t("Periodic inspections look for visible leaks, wear and deterioration so that repairs can be prioritized early. These examples show how an unattended issue can develop—not a prediction for every property.","Las inspecciones periódicas buscan fugas, desgaste y deterioro visibles para priorizar las reparaciones a tiempo. Estos ejemplos muestran cómo puede evolucionar un problema sin atender; no significa que ocurrirá en todas las propiedades."))}<div class="prevention-list">'
 for a,b,d,f in risks:out+=f'<div><span>{t(a,b)}</span><b aria-hidden="true">→</b><span>{t(d,f)}</span></div>'
 out+='</div></div></section>'
 audiences=[('Apartment Buildings','Edificios de Apartamentos'),('Multifamily Properties','Propiedades Multifamiliares'),('Commercial Properties','Propiedades Comerciales'),('Property Managers','Administradores de Propiedades'),('Building Owners','Propietarios de Edificios'),('General Contractors','Contratistas Generales')]
 out+=f'<section class="section"><div class="wrap">{title(t("BUILT FOR PROPERTY OWNERS & MANAGERS","PENSADO PARA PROPIETARIOS Y ADMINISTRADORES"),t("For the buildings you own, manage and maintain.","Para los edificios que posee, administra y mantiene."),t("From apartment and multifamily buildings to small commercial properties, coordinate recurring maintenance through one working relationship.","Desde edificios de apartamentos y multifamiliares hasta pequeñas propiedades comerciales, coordine el mantenimiento recurrente mediante una sola relación de servicio."))}<div class="audience-grid">'
 for i,a in enumerate(audiences):out+=f'<article><span class="step-number">0{i+1}</span><h3>{c(a)}</h3></article>'
 out+='</div></div></section>'
 factors=('Property size|Number of units|Required services|Inspection frequency|Expected maintenance workload|Response requirements','Tamaño de la propiedad|Número de unidades|Servicios requeridos|Frecuencia de inspecciones|Carga de mantenimiento prevista|Requisitos de respuesta')
 out+=f'<section class="section soft" id="maintenance-plans"><div class="wrap plan-layout"><div>{title(t("CUSTOM MAINTENANCE AGREEMENTS","ACUERDOS DE MANTENIMIENTO A MEDIDA"),t("A schedule that fits your building.","Un programa que se adapta a su edificio."),t("Maintenance agreements are customized around the property’s systems, priorities and service needs. Pricing and scope are established after the assessment.","Los acuerdos se adaptan a los sistemas, prioridades y necesidades de la propiedad. El precio y el alcance se establecen después de la evaluación."))}<ul class="checks">'+''.join(f'<li>{a}</li>' for a in c(factors).split('|'))+'</ul></div><div class="plan-panel"><p class="eyebrow">'+t('EXAMPLE SERVICE FREQUENCIES','EJEMPLOS DE FRECUENCIA')+'</p><div class="frequency-grid">'
 for a in [('Monthly','Mensual'),('Biweekly','Cada Dos Semanas'),('Weekly','Semanal'),('Custom Schedule','Calendario Personalizado')]:out+=f'<span>{c(a)}</span>'
 out+=f'</div><p>{t("Request a property assessment to receive a customized maintenance proposal.","Solicite una evaluación de su propiedad para recibir una propuesta de mantenimiento personalizada.")}</p>{cta()}</div></div></section>'
 out+=maintenance_form(t,link)
 return out

def maintenance_form(t,link):
 fields=[('name',('Name','Nombre'),'text','name',True),('company',('Company / Property Name','Empresa / Nombre de la Propiedad'),'text','organization',True),('phone',('Phone','Teléfono'),'tel','tel',True),('email',('Email','Correo Electrónico'),'email','email',True),('address',('Property Address','Dirección de la Propiedad'),'text','street-address',True),('units',('Number of Units (optional)','Número de Unidades (opcional)'),'number','off',False)]
 inputs=''
 for id,label,kind,auto,required in fields:
  inputs+=f'<div class="field"><label for="building-{id}">{t(*label)}{" *" if required else ""}</label><input id="building-{id}" name="{id}" type="{kind}" autocomplete="{auto}" {"required" if required else ""} {"min=1 max=100000 step=1" if kind=="number" else "maxlength=200"}></div>'
 options=[('property_type',('Property Type','Tipo de Propiedad'),[('apartment','Apartment Building','Edificio de Apartamentos'),('multifamily','Multifamily Property','Propiedad Multifamiliar'),('commercial','Commercial Property','Propiedad Comercial'),('mixed','Mixed-use Building','Edificio de Uso Mixto'),('other','Other','Otro')]),('maintenance_type',('Type of Maintenance Needed','Tipo de Mantenimiento Necesario'),[('comprehensive','Ongoing Building Maintenance','Mantenimiento Continuo del Edificio'),('plumbing','Plumbing Maintenance','Mantenimiento de Plomería'),('preventive','Preventive Inspections','Inspecciones Preventivas'),('repairs','Building Repairs & Common Areas','Reparaciones y Áreas Comunes'),('custom','Custom Scope / Several Services','Alcance Personalizado / Varios Servicios')]),('frequency',('Preferred Maintenance Frequency','Frecuencia de Mantenimiento Preferida'),[('monthly','Monthly','Mensual'),('biweekly','Biweekly','Cada Dos Semanas'),('weekly','Weekly','Semanal'),('custom','Custom Schedule','Calendario Personalizado'),('unsure','Discuss during assessment','Definir durante la evaluación')])]
 for id,label,values in options:
  inputs+=f'<div class="field"><label for="building-{id}">{t(*label)} *</label><select id="building-{id}" name="{id}" required><option value="">{t("Select an option","Seleccione una opción")}</option>'+''.join(f'<option value="{value}">{t(en,es)}</option>' for value,en,es in values)+'</select></div>'
 return f'''<section class="section" id="maintenance-assessment"><div class="wrap building-contact"><div><p class="eyebrow">{t('LET’S PLAN YOUR PROPERTY’S CARE','PLANIFIQUEMOS EL CUIDADO DE SU PROPIEDAD')}</p><h2>{t('Start with a property assessment.','Comience con una evaluación de su propiedad.')}</h2><p>{t('Tell us about the building and the support you need. We’ll review your priorities and discuss a maintenance proposal with a defined scope.','Cuéntenos sobre el edificio y el apoyo que necesita. Revisaremos sus prioridades para conversar sobre una propuesta con un alcance definido.')}</p><a class="contact-phone" href="tel:+12393337935">(239) 333-7935</a><p>{t('New York • New Jersey<br>Staten Island • Long Island','Nueva York • Nueva Jersey<br>Staten Island • Long Island')}</p><p class="scope-note">{t('Submitting an inquiry does not confirm a service agreement or response time. These details are established in your maintenance plan.','Enviar una consulta no confirma un acuerdo de servicio ni un tiempo de respuesta. Estos detalles se establecen en su plan de mantenimiento.')}</p></div><div class="estimate-panel"><h2>{t('Your building. Your plan.','Su edificio. Su plan.')}</h2><p>{t('Complete the form to prepare a WhatsApp message. Review it and send it in WhatsApp.','Complete el formulario para preparar un mensaje de WhatsApp. Revíselo y envíelo desde WhatsApp.')}</p><form id="maintenance-form" data-inquiry="maintenance">{inputs}<div class="field full"><label for="building-message">{t('Message','Mensaje')} *</label><textarea id="building-message" name="message" rows="4" maxlength="2000" required></textarea></div><p class="form-note full">{t('Fields marked * are required. Your information is shared with WhatsApp when you continue.','Los campos con * son obligatorios. Su información se comparte con WhatsApp cuando continúa.')} <a href="{link('privacy')}">{t('Privacy Policy','Política de Privacidad')}</a>.</p><button class="btn full" type="submit">{t('Request Maintenance Assessment','Solicitar Evaluación de Mantenimiento')} ↗</button><p class="form-status full" role="status" aria-live="polite"></p></form><noscript><p>{t('Enable JavaScript to prepare the form, or call us directly.','Active JavaScript para preparar el formulario o llámenos directamente.')}</p></noscript></div></div></section>'''

def division_links(t,link,key):
 return '<nav class="division-nav" aria-label="'+t('Main service divisions','Divisiones principales')+'"><div class="wrap">'+''.join(f'<a class="division-link {"plumbing-division" if k=="plumbing" else ""}" href="{link(k)}" {"aria-current=page" if key==k else ""}>{t(*label)} <span aria-hidden="true">↗</span></a>' for k,label in [('plumbing',('Plumbing','Plomería')),('maintenance',('Building Maintenance','Mantenimiento de Edificios'))])+'</div></nav>'

def division_cards(t,photo,link):
 return f'''<section class="section divisions-section"><div class="wrap"><div class="section-heading"><p class="eyebrow">{t('TWO DIVISIONS. ONE NEXTPRO.','DOS DIVISIONES. UN SOLO NEXTPRO.')}</p><h2>{t('Plumbing expertise. Ongoing building care.','Experiencia en plomería. Cuidado continuo de edificios.')}</h2></div><div class="division-cards"><article class="card division-card primary">{photo('32588548',t('Plumbing repair specialist','Especialista en reparación de plomería'))}<div class="card-body"><p class="eyebrow">{t('OUR CORE SPECIALTY','NUESTRA ESPECIALIDAD PRINCIPAL')}</p><h3>{t('Plumbing','Plomería')}</h3><p>{t('Repairs, installations and plumbing solutions for homes and businesses. Explore our complete range of services.','Reparaciones, instalaciones y soluciones de plomería para hogares y negocios. Conozca nuestra gama completa de servicios.')}</p><a class="btn" href="{link('plumbing')}">{t('Explore Plumbing','Explorar Plomería')} ↗</a></div></article><article class="card division-card">{photo('8293639',t('Professional building inspection','Inspección profesional de un edificio'))}<div class="card-body"><p class="eyebrow">{t('YOUR ONGOING MAINTENANCE PARTNER','SU ALIADO DE MANTENIMIENTO CONTINUO')}</p><h3>{t('Building Maintenance','Mantenimiento de Edificios')}</h3><p>{t('Recurring maintenance agreements, preventive inspections and coordinated repairs for building owners, property managers and contractors.','Acuerdos de mantenimiento recurrente, inspecciones preventivas y reparaciones coordinadas para propietarios, administradores y contratistas.')}</p><a class="btn dark" href="{link('maintenance')}">{t('Explore Building Maintenance','Explorar Mantenimiento de Edificios')} ↗</a></div></article></div></div></section>'''
