"""Generate the existing static NextPro website in English and Spanish.
Run: python3 build_v3.py. Set the production origin in v3-config.json first.
"""
from pathlib import Path
from building_maintenance import maintenance_page, division_links, division_cards
import json, html, posixpath
from urllib.parse import quote
ROOT=Path(__file__).resolve().parent
CONFIG=json.loads((ROOT/'v3-config.json').read_text())
ORIGIN=CONFIG['site_url'].rstrip('/')
NAME='NextPro Plumbing & Maintenance'
PHONE='(239) 333-7935'
TEL='tel:+12393337935'
HERO='31287022'
# English and Spanish content are rendered into real HTML, including metadata.
SERVICES=[
('leaks',('Leak Repair','Reparación de Fugas'),('Leak Repair','Fugas'),
 ('Small leaks deserve a careful look. We inspect visible connections, identify the affected parts and discuss a practical repair before work begins.','Las fugas pequeñas merecen atención. Revisamos las conexiones visibles, identificamos las piezas afectadas y explicamos la reparación antes de empezar.'),
 ('Leaking pipes|Under-sink leaks|Supply line leaks|Connections|Shutoff valves|Toilet connection leaks|Visible water leaks','Tuberías con fugas|Fugas bajo el lavamanos|Fugas en líneas de suministro|Conexiones|Válvulas de cierre|Fugas en conexiones de inodoros|Fugas de agua visibles'),'32588548',('Plumber tightening a pipe connection with a wrench','Plomero ajustando una conexión de tubería con una llave')),
('pipes',('Pipe Repair','Reparación de Tuberías'),('Pipe Repair','Tuberías'),
 ('Restore the connections your property depends on. We assess accessible damaged pipework and select a repair approach suited to the material and condition.','Restablecemos las conexiones que su propiedad necesita. Evaluamos las tuberías dañadas accesibles y elegimos una reparación adecuada para su material y condición.'),
 ('Damaged pipes|PVC|Copper|PEX|Connections|Replacement of damaged sections','Tuberías dañadas|PVC|Cobre|PEX|Conexiones|Reemplazo de tramos dañados'),'29226620',('Technician fitting a pipe connection with hand tools','Técnico ajustando una conexión de tubería con herramientas')),
('faucets',('Faucet & Sink Repair','Grifos y Lavamanos'),('Faucets & Sinks','Grifos y Lavamanos'),
 ('From a persistent drip to a replacement sink, get help with the fixtures you use every day and the supply and drain connections behind them.','Desde un goteo constante hasta el reemplazo de un lavamanos, atendemos los accesorios de uso diario y sus conexiones de suministro y desagüe.'),
 ('Faucet replacement|Faucet leaks|Sink plumbing|Supply lines|Drain connections|P-traps|Shutoff valves','Reemplazo de grifos|Fugas en grifos|Plomería de lavamanos|Líneas de suministro|Conexiones de desagüe|Sifones tipo P|Válvulas de cierre'),'34295404',('Chrome faucet with marble backsplash','Grifo cromado frente a un revestimiento de mármol')),
('toilets',('Toilet Repair & Installation','Reparación e Instalación de Inodoros'),('Toilets','Inodoros'),
 ('A toilet should fill, flush and seal correctly. We troubleshoot running or leaking toilets, replace worn components and plan complete replacements when needed.','Un inodoro debe llenar, descargar y sellar correctamente. Revisamos pérdidas de agua, reemplazamos componentes desgastados y planificamos cambios completos cuando sea necesario.'),
 ('Clogged toilets|Running toilets|Leaking toilets|Wax ring|Fill valve|Flush valve|Toilet replacement|New toilet installation|Drain connection','Inodoros obstruidos|Descarga continua|Inodoros con fugas|Anillo de cera|Válvula de llenado|Válvula de descarga|Reemplazo de inodoros|Instalación de inodoros nuevos|Conexión al desagüe'),'31267707',('Toilet, basin and shower in a modern bathroom','Inodoro, lavamanos y ducha en un baño moderno')),
('drains',('Drain & Clog Services','Drenajes y Obstrucciones'),('Drain Cleaning','Drenajes'),
 ('Slow drainage can interrupt your whole routine. Tell us which fixtures are affected so we can assess the blockage and discuss the right next step.','Un drenaje lento puede interrumpir su rutina. Cuéntenos cuáles accesorios están afectados para evaluar la obstrucción y explicar el siguiente paso.'),
 ('Slow drains|Clogged sinks|Bathroom drains|Kitchen drains|Toilet clogs|Drain troubleshooting','Drenajes lentos|Lavamanos obstruidos|Drenajes de baño|Drenajes de cocina|Inodoros tapados|Diagnóstico de drenajes'),'26492611',('Drain plunger used for household clog clearing','Destapador utilizado para obstrucciones domésticas')),
('kitchen',('Kitchen Plumbing','Plomería de Cocina'),('Kitchen Plumbing','Cocina'),
 ('Keep the heart of your home working smoothly. We handle sink and faucet repairs, accessible water lines and the drain connections inside your kitchen cabinets.','Mantenga funcionando el corazón de su hogar. Atendemos fregaderos, grifos, líneas de agua accesibles y conexiones de desagüe dentro de los gabinetes.'),
 ('Kitchen sinks|Faucets|Drain lines|P-traps|Water supply|Shutoff valves|Dishwasher plumbing connections where applicable','Fregaderos de cocina|Grifos|Líneas de desagüe|Sifones tipo P|Suministro de agua|Válvulas de cierre|Conexiones de lavavajillas cuando corresponda'),'kitchen-work',('Plumbing work at a kitchen sink','Trabajo de plomería en un fregadero de cocina')),
('bathroom',('Bathroom Plumbing','Plomería de Baño'),('Bathroom Plumbing','Baños'),
 ('Practical repairs and considered fixture updates for a room that works hard every day. We review the existing connections before planning the work.','Reparaciones prácticas y renovación de accesorios para un espacio de uso diario. Revisamos las conexiones existentes antes de planificar el trabajo.'),
 ('Toilets|Sinks|Faucets|Drain connections|Water supply|Fixture replacement|Plumbing repairs','Inodoros|Lavamanos|Grifos|Conexiones de desagüe|Suministro de agua|Reemplazo de accesorios|Reparaciones de plomería'),'7745981',('Bathroom basin and wall-mounted plumbing fixtures','Lavamanos y accesorios de plomería en un baño')),
('water-lines',('Water Supply Lines','Líneas de Agua'),('Water Lines','Líneas de Agua'),
 ('Water delivery starts with sound connections. We inspect accessible supply lines, valves and fittings, and repair or replace affected sections as appropriate.','El suministro de agua comienza con buenas conexiones. Revisamos líneas accesibles, válvulas y uniones para reparar o reemplazar los tramos afectados según corresponda.'),
 ('PEX|Copper|Supply connections|Shutoff valves|Repair|Replacement of accessible damaged sections','PEX|Cobre|Conexiones de suministro|Válvulas de cierre|Reparación|Reemplazo de tramos dañados accesibles'),'3721272',('Close-up of a copper pipe and elbow connection','Detalle de tubería de cobre y conexión en codo')),
('fixtures',('Fixture Installation','Instalación de Accesorios'),('Fixture Installation','Accesorios'),
 ('Make an update feel complete. We review fixture compatibility, existing connections and the installation requirements before fitting your new equipment.','Complete la renovación de su espacio. Revisamos la compatibilidad, las conexiones existentes y los requisitos de instalación antes de colocar sus accesorios nuevos.'),
 ('Faucets|Sinks|Toilets|Valves|Plumbing fixtures|Connections','Grifos|Lavamanos|Inodoros|Válvulas|Accesorios de plomería|Conexiones'),'4048080',('Chrome plumbing fixture in a bathroom','Accesorio cromado de plomería en un baño')),
('residential',('Residential Plumbing','Plomería Residencial'),('Residential','Residencial'),
 ('For the place you call home and the properties you care for. Share the issue, location and access details so we can coordinate a sensible service plan.','Para su hogar y las propiedades que cuida. Comparta el problema, la ubicación y los detalles de acceso para coordinar un plan de servicio adecuado.'),
 ('Houses|Apartments|Condos|Landlords|Property owners','Casas|Apartamentos|Condominios|Arrendadores|Propietarios'),'186077',('Residential house exterior at dusk','Exterior de una vivienda al atardecer')),
('commercial',('Commercial Plumbing','Plomería Comercial'),('Commercial','Comercial'),
 ('Plumbing support for the spaces where business happens. We coordinate access and discuss the scope with owners and property managers before scheduling work.','Apoyo de plomería para los espacios donde opera su negocio. Coordinamos el acceso y definimos el alcance con propietarios y administradores antes de programar el trabajo.'),
 ('Offices|Retail|Small businesses|Commercial properties|Property managers','Oficinas|Locales comerciales|Pequeños negocios|Propiedades comerciales|Administradores de propiedades'),'380769',('Professional office with shared workspaces','Oficina profesional con espacios de trabajo compartidos')),
]
PAGES={
 'home':('index.html',('Home','Inicio'),('Professional Plumbing. Dependable Property Maintenance.','Plomería Profesional. Mantenimiento Confiable.'),('Practical plumbing and maintenance solutions for homes and businesses, with direct communication and bilingual service.','Soluciones prácticas de plomería y mantenimiento para hogares y negocios, con comunicación directa y atención bilingüe.')),
 'plumbing':('services/plumbing.html',('Plumbing','Plomería'),('Professional Plumbing Services','Servicios Profesionales de Plomería'),('Reliable plumbing repairs, installations and maintenance for homes and businesses.','Reparaciones, instalaciones y mantenimiento de plomería para hogares y negocios.')),
 'drain':('services/drain-cleaning.html',('Drain Cleaning','Destape de Drenajes'),('Get your drains flowing again.','Recupere el flujo de sus drenajes.'),('Drain cleaning and clog troubleshooting for kitchen sinks, bathrooms and toilets.','Destape de drenajes y diagnóstico de obstrucciones en cocinas, baños e inodoros.')),
 'heaters':('services/water-heaters.html',('Water Heaters','Calentadores de Agua'),('Hot water starts with the right solution.','El agua caliente empieza con la solución adecuada.'),('Water-heater troubleshooting, replacement planning and plumbing connections for your property.','Diagnóstico de calentadores de agua, planificación de reemplazos y conexiones de plomería para su propiedad.')),
 'maintenance':('services/maintenance.html',('Building Maintenance','Mantenimiento de Edificios'),('Building Maintenance Services','Servicios de Mantenimiento de Edificios'),('Building maintenance services in New York and New Jersey: recurring property care, preventive inspections and repairs for apartment and commercial buildings.','Mantenimiento de edificios en Nueva York y Nueva Jersey: planes recurrentes, inspecciones preventivas y reparaciones para propiedades residenciales y comerciales.')),
 'areas':('service-areas.html',('Service Areas','Áreas de Servicio'),('Local service. Direct communication.','Servicio local. Comunicación directa.'),('Serving New York, New Jersey, Staten Island and Long Island. Contact us to confirm availability for your location.','Atendemos Nueva York, Nueva Jersey, Staten Island y Long Island. Contáctenos para confirmar disponibilidad en su ubicación.')),
 'about':('about.html',('About','Nosotros'),('A practical approach. A personal connection.','Un enfoque práctico. Un trato personal.'),('Meet NextPro Plumbing & Maintenance: plumbing and property care with clear communication in English and Spanish.','Conozca NextPro Plumbing & Maintenance: plomería y cuidado de propiedades con comunicación clara en inglés y español.')),
 'contact':('contact.html',('Contact','Contacto'),('Tell us what your property needs.','Cuéntenos qué necesita su propiedad.'),('Request an estimate, ask a question or discuss your next repair directly with NextPro.','Solicite una cotización, haga una consulta o converse sobre su próxima reparación directamente con NextPro.')),
 'privacy':('privacy.html',('Privacy Policy','Política de Privacidad'),('Privacy Policy','Política de Privacidad'),('How this website handles the information you choose to share.','Cómo este sitio maneja la información que usted decide compartir.')),
 'terms':('terms.html',('Terms','Términos'),('Website & Service Inquiries','Sitio Web y Consultas de Servicio'),('Information about using this website and requesting services.','Información sobre el uso de este sitio y las solicitudes de servicio.')),
}
def e(s):return html.escape(str(s),quote=True)
def choose(pair):return pair[0 if LANG=='en' else 1]
def t(en,es):return choose((en,es))
def loc(key,lang=None):return ('es/' if (lang or LANG)=='es' else '')+PAGES[key][0]
def relative(path):return posixpath.relpath(path,posixpath.dirname(CURRENT) or '.')
def link(key,anchor='',lang=None):
 language=lang or LANG
 return relative(loc(key,language))+'?lang='+language+('#'+anchor if anchor else '')
def asset(name):return relative(name)
def photo(id,alt,lazy=True,cls=''):
 return f'<img class="{cls}" src="{asset("images/photo-"+str(id)+".webp")}" alt="{e(alt)}" width="1400" height="1000" loading="{"lazy" if lazy else "eager"}" decoding="async" {"" if lazy else "fetchpriority=high"}>'
def whatsapp():
 if CURRENT.endswith('services/maintenance.html'):
  return 'https://wa.me/12393337935?text='+quote(t('Hello NextPro Plumbing & Maintenance. I would like information about a building maintenance agreement.','Hola NextPro Plumbing & Maintenance. Quisiera información sobre un acuerdo de mantenimiento de edificios.'))
 return 'https://wa.me/12393337935?text='+quote(t('Hello NextPro Plumbing & Maintenance. I would like information about a plumbing service.','Hola NextPro Plumbing & Maintenance. Quisiera información sobre un servicio de plomería.'))
def wa(label='WhatsApp',cls='btn outline'):
 return f'<a class="{cls}" href="{whatsapp()}" target="_blank" rel="noopener noreferrer">{label} <span aria-hidden="true">↗</span></a>'
def buttons():return f'<div class="actions"><a class="btn" href="{link("contact","estimate")}">{t("Request an Estimate","Solicitar Cotización")} <span aria-hidden="true">↗</span></a><a class="btn outline" href="{TEL}">{t("Call Now","Llamar Ahora")}</a>{wa()}</div>'
def band():
 return f'<aside class="cta-band"><div class="wrap cta-inner"><div><p class="eyebrow">{t("LET’S TALK ABOUT YOUR PROJECT","HABLEMOS DE SU PROYECTO")}</p><h2>{t("Need Plumbing Help?","¿Necesita ayuda con su plomería?")}</h2><p>{t("Call NextPro Plumbing & Maintenance","NextPro Plumbing & Maintenance")}</p><a class="cta-phone" href="{TEL}">{PHONE}</a></div>{buttons()}</div></aside>'
def header(key):
 nav=''.join(f'<a href="{link(k)}" {"aria-current=page" if k==key else ""}>{choose(PAGES[k][1])}</a>' for k in ['home','plumbing','maintenance','drain','heaters','areas','about','contact'])
 langs=''.join(f'<a class="language {"selected" if LANG==l else ""}" href="{link(key,lang=l)}" data-language="{l}" lang="{l}" hreflang="{l}" aria-label="{label}" {"aria-current=true" if LANG==l else ""}><span aria-hidden="true">{flag}</span><span class="lang-full">{label}</span><span class="lang-short">{l.upper()}</span></a>' for l,flag,label in [('en','🇺🇸','English'),('es','🇪🇨','Español')])
 return f'''<a class="skip" href="#main">{t('Skip to content','Saltar al contenido')}</a><div class="top"><div class="wrap"><span>{t('SERVING','ATENDEMOS')} {t('NEW YORK • NEW JERSEY • STATEN ISLAND • LONG ISLAND','NUEVA YORK • NUEVA JERSEY • STATEN ISLAND • LONG ISLAND')}</span><a href="{TEL}">{PHONE} <span aria-hidden="true">↗</span></a></div></div><header class="nav"><div class="nav-inner"><a class="brand" href="{link('home')}" aria-label="NextPro — {t('Home','Inicio')}"><img src="{asset('images/nextpro-logo-v3.webp')}" alt="NextPro Plumbing & Maintenance" width="520" height="225"></a><nav id="primary-nav" class="menu" aria-label="{t('Main navigation','Navegación principal')}">{nav}</nav><div class="language-switch" aria-label="{t('Language','Idioma')}">{langs}</div><a class="btn header-call" href="{TEL}">{t('Call Now','Llamar Ahora')}</a><button class="hamburger" type="button" aria-controls="primary-nav" aria-expanded="false" aria-label="{t('Open menu','Abrir menú')}" data-open="{t('Open menu','Abrir menú')}" data-close="{t('Close menu','Cerrar menú')}"><span></span><span></span><span></span></button></div>{division_links(t,link,key)}</header>'''
def footer():
 sl=[('plumbing','',('Plumbing','Plomería')),('maintenance','',('Building Maintenance','Mantenimiento de Edificios')),('plumbing','leaks',('Leak Repair','Reparación de Fugas')),('drain','',('Drain Cleaning','Destape de Drenajes')),('plumbing','toilets',('Toilet Repair','Reparación de Inodoros')),('plumbing','faucets',('Faucets & Sinks','Grifos y Lavamanos')),('heaters','',('Water Heaters','Calentadores de Agua')),('plumbing','kitchen',('Kitchen Plumbing','Plomería de Cocina')),('plumbing','bathroom',('Bathroom Plumbing','Plomería de Baño'))]
 services=''.join(f'<a href="{link(k,a)}">{choose(n)}</a>' for k,a,n in sl)
 company=''.join(f'<a href="{link(k,a)}">{choose(n)}</a>' for k,a,n in [('home','',('Home','Inicio')),('about','',('About Us','Nosotros')),('areas','',('Service Areas','Áreas de Servicio')),('contact','',('Contact','Contacto')),('contact','estimate',('Request Estimate','Solicitar Cotización'))])
 return f'''<footer class="footer"><div class="wrap"><div class="footer-grid"><div class="footer-brand"><a href="{link('home')}"><img src="{asset('images/nextpro-logo-v3.webp')}" alt="NextPro Plumbing & Maintenance" width="520" height="225" loading="lazy"></a><h2>NextPro Plumbing & Maintenance</h2><p>{t('Professional plumbing and property maintenance services for residential and commercial properties.','Servicios profesionales de plomería y mantenimiento para propiedades residenciales y comerciales.')}</p><p class="bilingual">{t('English & Español.','Inglés y Español.')}</p></div><div><h3>{t('Services','Servicios')}</h3>{services}</div><div><h3>{t('Company','Empresa')}</h3>{company}</div><div class="footer-contact"><div><h3>{t('Contact','Contacto')}</h3><p>NextPro Plumbing & Maintenance<br>Richard Velez</p><a class="footer-phone" href="{TEL}">{PHONE}</a>{wa('WhatsApp','footer-wa')}</div><div><h3 class="area-title">{t('Service Areas','Áreas de Servicio')}</h3><p>{t('New York<br>New Jersey','Nueva York<br>Nueva Jersey')}<br>Staten Island<br>Long Island</p></div></div></div><div class="copyright"><span>© 2026 NextPro Plumbing & Maintenance. {t('All Rights Reserved.','Todos los derechos reservados.')}</span><div><a href="{link('privacy')}">{t('Privacy Policy','Política de Privacidad')}</a><a href="{link('terms')}">{t('Terms','Términos')}</a></div></div></div></footer>{wa('WhatsApp','floating-wa')}<div class="mobile-bar"><a href="{TEL}">☎ {t('CALL NOW','LLAMAR')}</a>{wa('WHATSAPP','mobile-wa')}</div>'''
def hero(key,img=HERO):
 img={'home':'kitchen-work','drain':'9551374','maintenance':'534151','areas':'186077','about':'30387007'}.get(key,img)
 _,_,title,desc=PAGES[key]
 return f'''<section class="hero"><div class="hero-photo">{photo(img,t('Residential property and plumbing fixtures','Propiedad residencial y accesorios de plomería'),False)}</div><div class="wrap hero-content"><p class="eyebrow">{t('YOUR PROPERTY. OUR PRIORITY.','SU PROPIEDAD. NUESTRA PRIORIDAD.')}</p><h1>{choose(title)}</h1><p class="hero-description">{choose(desc)}</p>{buttons()}<div class="hero-notes"><span>{t('Residential & Commercial','Residencial y Comercial')}</span><span>{t('English & Español','Inglés y Español')}</span></div></div><span class="hero-index" aria-hidden="true">NEXTPRO / {choose(PAGES[key][1]).upper()}</span></section>'''
def heading(eyebrow,title,desc=''):
 return f'<div class="section-heading"><p class="eyebrow">{eyebrow}</p><h2>{title}</h2>{"<p>"+desc+"</p>" if desc else ""}</div>'
def process():
 steps=[('Tell us what’s happening','Cuéntenos qué sucede','Share your location, the issue and a few photos through WhatsApp.','Comparta su ubicación, el problema y algunas fotos por WhatsApp.'),('Review the next step','Revisemos el siguiente paso','We discuss the visible issue, scope and estimate before scheduling.','Conversamos sobre el problema visible, el alcance y la cotización antes de programar.'),('Coordinate your service','Coordinemos su servicio','Agree on access and timing, with communication in your preferred language.','Acordamos el acceso y la fecha, con comunicación en su idioma preferido.')]
 return '<section class="section process"><div class="wrap">'+heading(t('SIMPLE FROM THE START','SENCILLO DESDE EL INICIO'),t('Good service starts with a conversation.','Un buen servicio comienza con una conversación.'))+'<div class="steps">'+''.join(f'<article><span class="step-number">0{i+1}</span><h3>{t(a,b)}</h3><p>{t(c,d)}</p></article>' for i,(a,b,c,d) in enumerate(steps))+'</div></div></section>'
def plumbing():
 nav=''.join(f'<a href="#{s[0]}"><span>{i+1:02d}</span>{choose(s[2])}<b aria-hidden="true">↗</b></a>' for i,s in enumerate(SERVICES))
 out=hero('plumbing')+f'<section class="quick-services"><div class="wrap"><div class="quick-heading"><h2>{t("Our Plumbing Services","Nuestros Servicios de Plomería")}</h2><p>{t("Find the help you need. Explore below.","Encuentre la ayuda que necesita. Explore los servicios.")}</p></div><nav class="quick-grid" aria-label="{t("Plumbing services","Servicios de plomería")}">{nav}</nav></div></section>'
 for i,s in enumerate(SERVICES):
  id,title,short,desc,items,img,alt=s
  extra=f'<a class="text-link" href="{link("drain")}">{t("View Drain Cleaning Services","Ver Servicios de Destape de Drenajes")} →</a>' if id=='drains' else ''
  out+=f'<section class="service-detail {"reverse" if i%2 else ""}" id="{id}"><div class="wrap detail"><div class="service-image">{photo(img,choose(alt))}<span class="photo-number" aria-hidden="true">{i+1:02d} / 11</span></div><div class="service-copy"><p class="eyebrow">{t("PLUMBING SERVICES","SERVICIOS DE PLOMERÍA")} / {i+1:02d}</p><h2>{choose(title)}</h2><p>{choose(desc)}</p><ul class="checks">'+''.join(f'<li>{e(item)}</li>' for item in choose(items).split('|'))+f'</ul>{extra}<div class="actions"><a class="btn" href="{link("contact","estimate")}">{t("Request Estimate","Solicitar Cotización")} ↗</a><a class="text-link" href="{TEL}">{t("Call Now","Llamar Ahora")} →</a></div></div></div></section>'
  if i in [2,5,8]:out+=band()
 return out+process()+band()
def home():
 cards=[('drain','26492611',('Clear the way for better drainage.','Recupere el flujo de sus drenajes.')),('heaters','water-heater',('Troubleshooting & replacement planning.','Diagnóstico y planificación de reemplazos.'))]
 out=hero('home')+division_cards(t,photo,link)+'<section class="section"><div class="wrap">'+heading(t('MORE FROM OUR PLUMBING DIVISION','MÁS DE NUESTRA DIVISIÓN DE PLOMERÍA'),t('Specialized care for everyday systems.','Atención especializada para sus sistemas cotidianos.'),t('From the first dripping faucet to your next property update, start with the right conversation.','Desde el primer grifo que gotea hasta la próxima mejora de su propiedad, comience con la conversación adecuada.'))+'<div class="service-cards">'
 for key,img,desc in cards:out+=f'<article class="card">{photo(img,choose(PAGES[key][1]))}<div class="card-body"><h3>{choose(PAGES[key][1])}</h3><p>{choose(desc)}</p><a class="text-link" href="{link(key)}">{t("Explore Services","Explorar Servicios")} →</a></div></article>'
 out+='</div></div></section><section class="section soft"><div class="wrap intro-split"><div>'+heading(t('HOMES. BUSINESSES. PEOPLE.','HOGARES. NEGOCIOS. PERSONAS.'),t('The details matter. So does your peace of mind.','Los detalles importan. Su tranquilidad también.'))+f'<p>{t("Work with NextPro for practical plumbing repairs and property maintenance. Speak directly with Richard Velez in English or Spanish, explain what you need and review the next step.","Cuente con NextPro para reparaciones prácticas de plomería y mantenimiento. Hable directamente con Richard Velez en inglés o español, explique lo que necesita y revise el siguiente paso.")}</p><a class="text-link" href="{link("about")}">{t("Get to know NextPro","Conozca NextPro")} →</a></div><div class="intro-image">{photo("186077",t("Home exterior","Exterior de una vivienda"))}</div></div></section>'
 return out+process()+band()
def service_page(key):
 data={
 'drain':('26492611',('A blockage needs the right approach.','Una obstrucción necesita el enfoque adecuado.'),('Tell us where water is backing up, how long it has been happening and whether more than one fixture is affected. We assess the symptoms and discuss appropriate clearing or repair options.','Indíquenos dónde se acumula el agua, desde cuándo sucede y si afecta más de un accesorio. Evaluamos los síntomas y conversamos sobre las opciones de destape o reparación.'),('Slow or standing water|Clogged kitchen sinks|Bathroom sink and shower drains|Toilet clogs|Recurring blockages|Drain-line troubleshooting','Agua estancada o drenaje lento|Fregaderos de cocina tapados|Desagües de lavamanos y duchas|Inodoros obstruidos|Obstrucciones recurrentes|Diagnóstico de líneas de drenaje')),
 'heaters':('water-heater',('Make the next step an informed one.','Tome una decisión bien informada.'),('Tell us about inconsistent temperatures, visible leaks or a unit that is no longer meeting your needs. Share the model, fuel type and photos of the connections so we can discuss the scope and site requirements.','Cuéntenos sobre temperaturas inestables, fugas visibles o un equipo que ya no cubre sus necesidades. Comparta el modelo, tipo de energía y fotos de las conexiones para conversar sobre el alcance y los requisitos del lugar.'),('Hot-water troubleshooting|Visible connection leaks|Water supply connections|Replacement planning|Installation requirements|Review of access and existing equipment','Diagnóstico de agua caliente|Fugas visibles en conexiones|Conexiones de suministro de agua|Planificación de reemplazo|Requisitos de instalación|Revisión del acceso y equipo existente')),
 'maintenance':('1505798577917-a65157d3320a',('Small repairs. A better-running property.','Pequeñas reparaciones. Una propiedad que funciona mejor.'),('Bring your repair list to one conversation. We review the condition, priorities and access needs to help plan practical maintenance for your home, rental or business.','Comparta su lista de reparaciones en una sola conversación. Revisamos el estado, las prioridades y el acceso para planificar el mantenimiento de su hogar, alquiler o negocio.'),('General property repairs|Plumbing fixture checks|Accessible connection checks|Fixture replacement|Rental-property maintenance coordination|Planned maintenance visits','Reparaciones generales de la propiedad|Revisión de accesorios de plomería|Revisión de conexiones accesibles|Reemplazo de accesorios|Coordinación de mantenimiento de alquileres|Visitas de mantenimiento planificadas'))}
 img,title,desc,items=data[key]
 out=hero(key)+f'<section class="section"><div class="wrap detail"><div class="service-image">{photo(img,choose(PAGES[key][1]))}</div><div class="service-copy"><p class="eyebrow">{t("A CLOSER LOOK","CONOZCA EL SERVICIO")}</p><h2>{choose(title)}</h2><p>{choose(desc)}</p><ul class="checks">'+''.join(f'<li>{s}</li>' for s in choose(items).split('|'))+'</ul>'+buttons()+'</div></div></section>'
 qs=[(t('What should I send with my inquiry?','¿Qué debo enviar con mi consulta?'),t('Your city, a description of the issue and clear photos. For water heaters, include the model label and visible connections.','Su ciudad, una descripción del problema y fotos claras. Para calentadores, incluya la etiqueta del modelo y las conexiones visibles.')),(t('How is an estimate prepared?','¿Cómo se prepara una cotización?'),t('The scope depends on the condition, access, materials and work required. We discuss the information provided and confirm whether an on-site review is needed.','El alcance depende del estado, acceso, materiales y trabajo necesario. Revisamos la información proporcionada y confirmamos si hace falta una visita.')),(t('Can I speak with someone in Spanish?','¿Puedo recibir atención en español?'),t('Yes. Contact NextPro in English or Spanish by phone or WhatsApp.','Sí. Comuníquese con NextPro en inglés o español por teléfono o WhatsApp.'))]
 out+='<section class="section soft"><div class="wrap faq">'+heading(t('BEFORE YOU GET STARTED','ANTES DE EMPEZAR'),t('A few helpful answers.','Algunas respuestas útiles.'))+''.join(f'<details><summary>{q}</summary><p>{a}</p></details>' for q,a in qs)+'</div></section>'
 return out+process()+band()
def areas():
 names=[('New York','Nueva York'),('New Jersey','Nueva Jersey'),('Staten Island','Staten Island'),('Long Island','Long Island')]
 return hero('areas')+'<section class="section"><div class="wrap">'+heading(t('WHERE WE WORK','DÓNDE TRABAJAMOS'),t('Service across four areas.','Servicio en cuatro áreas.'),t('Share your city or ZIP code so we can confirm coverage and coordinate access.','Comparta su ciudad o código postal para confirmar cobertura y coordinar el acceso.'))+'<div class="area-grid">'+''.join(f'<article><span class="eyebrow">0{i+1}</span><h2>{choose(n)}</h2><p>{t("Residential and commercial service inquiries.","Consultas de servicio residencial y comercial.")}</p><a class="text-link" href="{link("contact","estimate")}">{t("Check availability","Consultar disponibilidad")} →</a></article>' for i,n in enumerate(names))+'</div></div></section>'+band()
def about():
 return hero('about')+f'<section class="section"><div class="wrap intro-split"><div>{heading(t("MEET NEXTPRO","CONOZCA NEXTPRO"),t("Property care with a direct point of contact.","Cuidado de su propiedad con un contacto directo."))}<p>{t("NextPro Plumbing & Maintenance serves residential and commercial properties in New York, New Jersey, Staten Island and Long Island. Richard Velez is your contact for discussing plumbing repairs, fixture installation and property maintenance.","NextPro Plumbing & Maintenance atiende propiedades residenciales y comerciales en Nueva York, Nueva Jersey, Staten Island y Long Island. Richard Velez es su contacto para conversar sobre reparaciones de plomería, instalación de accesorios y mantenimiento.")}</p><p>{t("Our approach is straightforward: understand the issue, discuss the work and coordinate the next step. Communication is available in English and Spanish.","Nuestro enfoque es sencillo: comprender el problema, explicar el trabajo y coordinar el siguiente paso. Ofrecemos comunicación en inglés y español.")}</p>{buttons()}</div><div class="intro-image">{photo("31267707",t("Modern bathroom and plumbing fixtures","Baño moderno y accesorios de plomería"))}</div></div></section>'+process()+band()
def contact():
 opts=''.join(f'<option value="{e(choose(PAGES[k][1]))}">{choose(PAGES[k][1])}</option>' for k in ['plumbing','drain','heaters','maintenance'])
 fields=[('name',t('Full name','Nombre completo'),'text','name'),('phone',t('Phone number','Número de teléfono'),'tel','tel'),('city',t('City / ZIP code','Ciudad / Código postal'),'text','address-level2')]
 form=''.join(f'<div class="field"><label for="{id}">{label} <span aria-hidden="true">*</span></label><input id="{id}" name="{id}" type="{type}" autocomplete="{auto}" required maxlength="120" ></div>' for id,label,type,auto in fields)
 return f'''<section class="page-heading"><div class="wrap"><p class="eyebrow">{t('LET’S GET STARTED','COMENCEMOS')}</p><h1>{choose(PAGES['contact'][2])}</h1><p>{choose(PAGES['contact'][3])}</p></div></section><section class="section contact-section"><div class="wrap contact-grid"><div><p class="eyebrow">{t('DIRECT CONTACT','CONTACTO DIRECTO')}</p><h2>{t('A real conversation. A clear next step.','Una conversación directa. Un siguiente paso claro.')}</h2><p>{t('Speak with Richard Velez about your property. Service available in English and Spanish.','Hable con Richard Velez sobre su propiedad. Atención disponible en inglés y español.')}</p><a class="contact-phone" href="{TEL}">{PHONE}</a>{wa('WhatsApp','btn dark')}<div class="contact-note"><h3>{t('Before you contact us','Antes de contactarnos')}</h3><p>{t('Have your location, a brief description and photos ready. Please confirm service availability before planning your visit.','Tenga a mano su ubicación, una descripción breve y fotos. Confirme la disponibilidad del servicio antes de planificar la visita.')}</p></div></div><div class="estimate-panel" id="estimate"><p class="eyebrow">{t('REQUEST AN ESTIMATE','SOLICITAR COTIZACIÓN')}</p><h2>{t('How can we help?','¿Cómo podemos ayudarle?')}</h2><p>{t('Complete the form to prepare a WhatsApp message. You review and send it in WhatsApp.','Complete el formulario para preparar un mensaje de WhatsApp. Usted lo revisa y envía desde WhatsApp.')}</p><form id="estimate-form">{form}<div class="field"><label for="service">{t('Service','Servicio')} *</label><select id="service" name="service" required><option value="">{t('Select a service','Seleccione un servicio')}</option>{opts}<option>{t('Other / Not sure','Otro / No estoy seguro')}</option></select></div><div class="field full"><label for="message">{t('Tell us about the problem','Cuéntenos sobre el problema')} *</label><textarea id="message" name="message" rows="4" maxlength="2000" required></textarea></div><p class="form-note full">{t('Required fields are marked *. Your message is shared with WhatsApp only when you continue.','Los campos obligatorios llevan *. Su mensaje se comparte con WhatsApp solo cuando continúa.')} <a href="{link('privacy')}">{t('Privacy Policy','Política de Privacidad')}</a>.</p><button class="btn full" type="submit">{t('Continue to WhatsApp','Continuar a WhatsApp')} ↗</button><p class="form-status full" role="status" aria-live="polite"></p></form><noscript><p>{t('Please enable JavaScript to prepare the form, or contact us by phone or WhatsApp.','Active JavaScript para preparar el formulario o contáctenos por teléfono o WhatsApp.')}</p>{wa()}</noscript></div></div></section>'''
def legal(key):
 if key=='privacy':
  sections=[('Information you provide','Información que proporciona','The estimate and maintenance assessment forms prepare a message with the information you enter. This may include your name, company or property name, phone number, email, property address, type, optional unit count, service needs, preferred frequency and description. This static website does not submit the form to a NextPro database. When you continue, these details are included in a WhatsApp link.','Los formularios de cotización y evaluación de mantenimiento preparan un mensaje con los datos que ingresa. Pueden incluir nombre, empresa o propiedad, teléfono, correo, dirección, tipo de propiedad, número opcional de unidades, servicios, frecuencia preferida y descripción. Este sitio estático no envía el formulario a una base de datos de NextPro. Al continuar, los detalles se incluyen en un enlace de WhatsApp.'),('Language preference','Preferencia de idioma','Your browser stores your language choice locally so that it can be remembered between pages. If you switch languages while completing a form, its draft is held temporarily in session storage and restored on the translated page. You can change it using the language selector or clear it in your browser settings. This site does not include advertising or analytics scripts.','Su navegador guarda localmente su idioma para recordarlo entre páginas. Si cambia de idioma mientras completa un formulario, el borrador se conserva temporalmente en el almacenamiento de sesión y se recupera en la página traducida. Puede cambiarlo con el selector o borrarlo en la configuración del navegador. Este sitio no incluye scripts de publicidad ni analítica.'),('External services','Servicios externos','WhatsApp and your phone provider handle communications under their own policies. The website hosting provider may process technical request logs. Avoid sharing sensitive personal information in your inquiry.','WhatsApp y su proveedor telefónico gestionan las comunicaciones según sus propias políticas. El proveedor de alojamiento puede procesar registros técnicos de solicitudes. Evite compartir información personal sensible en su consulta.'),('Questions','Consultas','For questions about information shared with NextPro, contact Richard Velez at (239) 333-7935.','Para consultas sobre información compartida con NextPro, contacte a Richard Velez al (239) 333-7935.')]
 else:
  sections=[('Website information','Información del sitio','Service descriptions provide general information. The work available for a specific property depends on the issue, access, site conditions and applicable requirements.','Las descripciones ofrecen información general. El trabajo disponible para una propiedad depende del problema, acceso, condiciones del lugar y requisitos aplicables.'),('Estimates and scheduling','Cotizaciones y programación','Sending an inquiry does not confirm an appointment, price or agreement to perform work. Scope, price and scheduling must be discussed and agreed directly with NextPro before work starts.','Enviar una consulta no confirma una cita, precio ni acuerdo de trabajo. El alcance, precio y fecha deben conversarse y acordarse directamente con NextPro antes de comenzar.'),('Photography','Fotografías','Stock photographs illustrate service categories and property types. They do not depict verified NextPro projects, employees or completed jobs.','Las fotografías de banco de imágenes ilustran categorías de servicio y tipos de propiedades. No representan proyectos, empleados ni trabajos verificados de NextPro.'),('Contact','Contacto','Contact NextPro Plumbing & Maintenance at (239) 333-7935 with questions about a service or these website terms.','Contacte a NextPro Plumbing & Maintenance al (239) 333-7935 si tiene consultas sobre un servicio o estos términos.')]
 return f'<section class="page-heading"><div class="wrap"><p class="eyebrow">NEXTPRO</p><h1>{choose(PAGES[key][2])}</h1><p>{choose(PAGES[key][3])}</p></div></section><section class="section"><div class="wrap legal-copy">'+''.join(f'<h2>{t(a,b)}</h2><p>{t(c,d)}</p>' for a,b,c,d in sections)+'</div></section>'
def render(key):
 path,title,_,desc=PAGES[key]
 url=ORIGIN+'/'+CURRENT
 en=ORIGIN+'/'+loc(key,'en');es=ORIGIN+'/'+loc(key,'es')
 title=t('Plumbing & Building Maintenance | NY & NJ','Plomería y Mantenimiento de Edificios | NY y NJ') if key=='home' else choose(title)+' | NextPro Plumbing & Maintenance'
 if key=='maintenance':title=t('Building Maintenance Services | NY & NJ | NextPro','Mantenimiento de Edificios | NY y NJ | NextPro')
 body=maintenance_page(t,photo,link,wa) if key=='maintenance' else home() if key=='home' else plumbing() if key=='plumbing' else service_page(key) if key in ['drain','heaters','maintenance'] else areas() if key=='areas' else about() if key=='about' else contact() if key=='contact' else legal(key)
 schema={'@context':'https://schema.org','@graph':[{'@type':'Plumber','@id':ORIGIN+'/#business','name':NAME,'url':ORIGIN,'telephone':'+1-239-333-7935','logo':ORIGIN+'/images/nextpro-logo-v3.webp','areaServed':['New York','New Jersey','Staten Island','Long Island'],'contactPoint':{'@type':'ContactPoint','telephone':'+1-239-333-7935','contactType':'customer service','availableLanguage':['English','Spanish']}},{'@type':'WebPage','@id':url+'#page','url':url,'name':title,'description':choose(desc),'inLanguage':LANG,'about':{'@id':ORIGIN+'/#business'}}]}
 if key in ['plumbing','drain','heaters','maintenance']:schema['@graph'].append({'@type':'Service','name':choose(PAGES[key][1]),'serviceType':choose(PAGES[key][1]),'provider':{'@id':ORIGIN+'/#business'},'url':url,'areaServed':['New York','New Jersey','Staten Island','Long Island']})
 lang_config=json.dumps({'en':relative(loc(key,'en')),'es':relative(loc(key,'es'))})
 out=f'''<!doctype html>
<html lang="{LANG}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#081f32"><link rel="icon" href="{asset('favicon.ico')}"><title>{e(title)}</title><meta name="description" content="{e(choose(desc))}"><link rel="canonical" href="{url}"><link rel="alternate" hreflang="en" href="{en}"><link rel="alternate" hreflang="es" href="{es}"><link rel="alternate" hreflang="x-default" href="{en}"><meta property="og:type" content="website"><meta property="og:site_name" content="{e(NAME)}"><meta property="og:title" content="{e(title)}"><meta property="og:description" content="{e(choose(desc))}"><meta property="og:url" content="{url}"><meta property="og:locale" content="{t('en_US','es_EC')}"><meta property="og:locale:alternate" content="{t('es_EC','en_US')}"><meta property="og:image" content="{ORIGIN}/images/photo-{"8293639" if key=="maintenance" else HERO}.webp"><meta name="twitter:card" content="summary_large_image"><link rel="stylesheet" href="{asset('css/v2.css')}"><script id="language-routes" type="application/json">{lang_config}</script><script src="{asset('js/app.js')}" defer></script><script type="application/ld+json">{json.dumps(schema,ensure_ascii=False)}</script></head><body>{header(key)}<main id="main">{body}</main>{footer()}</body></html>'''
 # Keep all estimate links clean (the anchor is the final URL component).
 return out
urls=[]
for LANG in ['en','es']:
 for key in PAGES:
  CURRENT=loc(key)
  dest=ROOT/CURRENT;dest.parent.mkdir(parents=True,exist_ok=True);dest.write_text(render(key),encoding='utf-8');urls.append((key,LANG,CURRENT))
sitemap='<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">\n'
for key,lang,path in urls:
 sitemap+=f'<url><loc>{ORIGIN}/{path}</loc>'+''.join(f'<xhtml:link rel="alternate" hreflang="{l}" href="{ORIGIN}/{loc(key,l)}"/>' for l in ['en','es'])+f'<xhtml:link rel="alternate" hreflang="x-default" href="{ORIGIN}/{loc(key,"en")}"/></url>\n'
(ROOT/'sitemap.xml').write_text(sitemap+'</urlset>\n')
(ROOT/'robots.txt').write_text('User-agent: *\nAllow: /\nSitemap: '+ORIGIN+'/sitemap.xml\n')
print(f'Built {len(urls)} static pages. Site origin: {ORIGIN}')
